### PR TITLE
Fix evaluation

### PR DESCRIPTION
**Pull request by ma595**
This fixes the current visualisation (step 5) regression for `DEF_Trunk`. I have cherry-picked a commit from @tztsai and made a few modifications. This should be committed along with #45 

Once merged, SPINacc can be run end to end, and is ready for @dsgoll123 to check.

### CODE REVIEW

**Comment by dsgoll123** [comment]
I successfully ran task 1-5. The Eval*.png look plausible. I did a test with increased number of training data the Eval*.png show improved ML predictions - as expected. 



Two problems I encountered which are not directly related to the code modifications here

(1) README.md: 
The following action is not possible as file doesn't exist:
‘In tests/config.py you have to modify: test_path=/your/path/to/SPINacc/EXE_DIR/’ 
Should it be this file instead?  DEF_Trunk/config.py

(2) Running task 1-4 w/o any error message in log. I cannot locate the test results file listed in the log file ( I looked in EXE_DIR as specified as the last item in 'steps' of README). Entry from log file:
Task 1 reproducibility test results have been stored in tests_results.txt
Task 2 reproducibility test results have been stored in tests_results.txt
Task 3 reproducibility test results have been stored in tests_results.txt

**Comment by ma595** [comment]
@dsgoll123 In `DEF_Trunk/config.py` test_path should point to your output directory, so wherever `EXE_DIR` is. 

For (2), it looks like we're no longer outputting to `tests_results.txt` so this message is no longer valid. We have two options, we reproduce exactly what was there before (I'll checkout the old code to verify exactly what was in there. I suspect it was just a success or fail.) or delete this entirely.

**Comment by ma595** [comment]
I have looked at the previous version of `tests_results.txt` and it's a little more than I first thought. 

Reproducibility test for task 1 checks the element wise absolute error of `dist_all.npy` vs the reference (a (8,14) dimension array)
Reproducibility test for task 2 checks the contents of `IDloc.npy`, `IDSel.npy` and `IDx.npy` vs the reference. 
Reproducibility test for task 3 checks the contents of `SRF_FGSPIN.10Y.ORC22v8034_19101231_sechiba_rest.nc` vs the reference. (dimensions and variables)
Reproducibility test for task 4 checks all `*.png` files,
and contents of `SBG_FGSPIN.340Y.ORC22v8034_22501231_stomate_rest.nc`

**Comment by ma595** [comment]
@dsgoll123 Since the issues raised above are not directly related to the PR. I'll merge this PR for now. Thanks for the review.

**Pull request merged**
